// Bank data for DANA Virtual Account
export type BankType = "VA" | "DIRECT";

export interface Bank {
  id: string;
  name: string;
  fullName: string;
  type: BankType;
  prefix?: string; // Only for VA type
  logo: string;
  bgColor: string; // for logo background
  scale?: string; // Optional tailwind scale class for images with too much padding
}

export const BANKS: Bank[] = [
  // ── VA Prefix Banks ──────────────────────────────────────────────────────
  {
    id: "BCA",
    name: "BCA",
    fullName: "Bank Central Asia",
    type: "VA",
    prefix: "3901",
    logo: "/images/banks/BCA.png",
    bgColor: "#ffffff",
    scale: "scale-150",
  },
  {
    id: "BRI",
    name: "BRI",
    fullName: "Bank Rakyat Indonesia",
    type: "VA",
    prefix: "88810",
    logo: "/images/banks/BRI.png",
    bgColor: "#ffffff",
    scale: "scale-75",
  },
  {
    id: "BNI",
    name: "BNI",
    fullName: "Bank Negara Indonesia",
    type: "VA",
    prefix: "8810",
    logo: "/images/banks/BNI.png",
    bgColor: "#ffffff",
    scale: "scale-150",
  },
  {
    id: "MANDIRI",
    name: "Mandiri",
    fullName: "Bank Mandiri",
    type: "VA",
    prefix: "89508",
    logo: "/images/banks/MANDIRI.png",
    bgColor: "#ffffff",
    scale: "scale-150",
  },
  {
    id: "CIMB",
    name: "CIMB Niaga",
    fullName: "Bank CIMB Niaga",
    type: "VA",
    prefix: "8059",
    logo: "/images/banks/CIMB.png",
    bgColor: "#ffffff",
  },
  {
    id: "PERMATA",
    name: "Permata",
    fullName: "PermataBank",
    type: "VA",
    prefix: "8528",
    logo: "/images/banks/PERMATA.png",
    bgColor: "#ffffff",
    scale: "scale-150",
  },
  {
    id: "PANIN",
    name: "PaninBank",
    fullName: "Bank Pan Indonesia (PaninBank)",
    type: "VA",
    prefix: "8100",
    logo: "/images/banks/PANIN BANK.png",
    bgColor: "#ffffff",
  },
  {
    id: "BTN",
    name: "BTN",
    fullName: "Bank Tabungan Negara",
    type: "VA",
    prefix: "8528",
    logo: "/images/banks/BTN.png",
    bgColor: "#ffffff",
    scale: "scale-125",
  },

  // ── Direct Phone Banks ──────────────────────────────────────────────────
  {
    id: "ALLOBANK",
    name: "Allo Bank",
    fullName: "Allo Bank Indonesia",
    type: "DIRECT",
    logo: "/images/banks/ALLO BANK.png",
    bgColor: "#ffffff",
  },
  {
    id: "ACEH",
    name: "Bank Aceh Syariah",
    fullName: "Bank Aceh Syariah",
    type: "DIRECT",
    logo: "/images/banks/ACEH SYARIAH.png",
    bgColor: "#ffffff",
  },
  {
    id: "ALADIN",
    name: "Aladin Bank",
    fullName: "Bank Aladin Syariah",
    type: "DIRECT",
    logo: "/images/banks/ALADIN BANK.png",
    bgColor: "#ffffff",
  },
  {
    id: "BANTEN",
    name: "Bank Banten",
    fullName: "Bank Pembangunan Daerah Banten",
    type: "DIRECT",
    logo: "/images/banks/BANK BANTEN.png",
    bgColor: "#ffffff",
  },
  {
    id: "BJB",
    name: "BJB",
    fullName: "Bank BJB (Bank Jabar Banten)",
    type: "DIRECT",
    logo: "/images/banks/BJB.png",
    bgColor: "#ffffff",
  },
  {
    id: "CAPITAL",
    name: "Capital Indonesia",
    fullName: "Bank Capital Indonesia",
    type: "DIRECT",
    logo: "/images/banks/CAPITAL BANK.png",
    bgColor: "#ffffff",
  },
  {
    id: "DANAMON",
    name: "Danamon Syariah",
    fullName: "Bank Danamon Indonesia (Unit Usaha Syariah)",
    type: "DIRECT",
    logo: "/images/banks/DANAMIN SYARIAH.jpg",
    bgColor: "#ffffff",
    scale: "scale-125",
  },
  {
    id: "JAGO",
    name: "Bank Jago",
    fullName: "Bank Jago",
    type: "DIRECT",
    logo: "/images/banks/bank jago.png",
    bgColor: "#ffffff",
    scale: "scale-75",
  },
  {
    id: "JAGO_SYARIAH",
    name: "Jago Syariah",
    fullName: "Bank Jago (Unit Usaha Syariah)",
    type: "DIRECT",
    logo: "/images/banks/JAGO SYARIAH.png",
    bgColor: "#ffffff",
    scale: "scale-125",
  },
  {
    id: "DKI",
    name: "Bank DKI",
    fullName: "Bank DKI Jakarta",
    type: "DIRECT",
    logo: "/images/banks/BANK DKI.png",
    bgColor: "#ffffff",
  },
  {
    id: "JAMBI",
    name: "Bank Jambi",
    fullName: "Bank Pembangunan Daerah Jambi",
    type: "DIRECT",
    logo: "/images/banks/BANK JAMBI.png",
    bgColor: "#ffffff",
  },
  {
    id: "JATENG",
    name: "Bank Jateng",
    fullName: "Bank Pembangunan Daerah Jawa Tengah",
    type: "DIRECT",
    logo: "/images/banks/BANK JATENG.png",
    bgColor: "#ffffff",
  },
  {
    id: "JATIM",
    name: "Bank Jatim",
    fullName: "Bank Pembangunan Daerah Jawa Timur",
    type: "DIRECT",
    logo: "/images/banks/BANK JATIM.png",
    bgColor: "#ffffff",
  },
  {
    id: "KALBAR",
    name: "Bank Kalbar",
    fullName: "Bank Pembangunan Daerah Kalimantan Barat",
    type: "DIRECT",
    logo: "/images/banks/BANK KALBAR.png",
    bgColor: "#ffffff",
  },
  {
    id: "KALSEL",
    name: "Bank Kalsel",
    fullName: "Bank Pembangunan Daerah Kalimantan Selatan",
    type: "DIRECT",
    logo: "/images/banks/BANK KALSEL.png",
    bgColor: "#ffffff",
  },
  {
    id: "KALTENG",
    name: "Bank Kalteng",
    fullName: "Bank Pembangunan Daerah Kalimantan Tengah",
    type: "DIRECT",
    logo: "/images/banks/BANK KALTENG.jpg",
    bgColor: "#ffffff",
  },
  {
    id: "MEGA",
    name: "Bank Mega",
    fullName: "Bank Mega",
    type: "DIRECT",
    logo: "/images/banks/bank mega.png",
    bgColor: "#ffffff",
  },
  {
    id: "MEGA_SYARIAH",
    name: "Mega Syariah",
    fullName: "Bank Syariah Mega Indonesia",
    type: "DIRECT",
    logo: "/images/banks/MEGA SYARIAH.png",
    bgColor: "#ffffff",
  },
  {
    id: "NTT",
    name: "Bank NTT",
    fullName: "Bank Pembangunan Daerah Nusa Tenggara Timur",
    type: "DIRECT",
    logo: "/images/banks/BANK NTT.png",
    bgColor: "#ffffff",
  },
  {
    id: "PAPUA",
    name: "Bank Papua",
    fullName: "Bank Pembangunan Daerah Papua",
    type: "DIRECT",
    logo: "/images/banks/PAPUA BANK.png",
    bgColor: "#ffffff",
  },
  {
    id: "SAMPOERNA",
    name: "Sahabat Sampoerna",
    fullName: "Bank Sahabat Sampoerna",
    type: "DIRECT",
    logo: "/images/banks/Bank Sahabat Sampoerna.png",
    bgColor: "#ffffff",
  },
  {
    id: "KROM",
    name: "Krom Bank",
    fullName: "Krom Bank Indonesia",
    type: "DIRECT",
    logo: "/images/banks/Krom_Bank.png",
    bgColor: "#ffffff",
  },
  {
    id: "OCBC",
    name: "OCBC Indonesia",
    fullName: "OCBC Indonesia",
    type: "DIRECT",
    logo: "/images/banks/OCBC INDONESIA.png",
    bgColor: "#ffffff",
  },
  {
    id: "SEABANK",
    name: "SeaBank",
    fullName: "SeaBank Indonesia",
    type: "DIRECT",
    logo: "/images/banks/SEABANK.png",
    bgColor: "#ffffff",
  },
];

export function getVaNumber(bankId: string, danaPhone: string): string {
  const bank = BANKS.find((b) => b.id === bankId);
  if (!bank) return danaPhone;
  if (bank.type === "DIRECT") return danaPhone;
  return `${bank.prefix}${danaPhone}`;
}
